<a href="https://colab.research.google.com/github/superraihan/Python/blob/main/MD_RAIHAN_KABIR_NIBIR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Email Address: nibir777.bd@gmail.com

In [1]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


## Answer To The Q1

In [14]:
ages_array = np.array(ages)
salaries_array = np.array(salaries)

print("Ages Array:")
print(ages_array)

print("Salaries Array:")
print(salaries_array)

print("Ages Array Information:")
print("Data Type:", ages_array.dtype)
print("Number of Dimensions:", ages_array.ndim)
print("Shape:", ages_array.shape)
print("Size:", ages_array.size)

print("Salaries Array Information:")
print("Data Type:", salaries_array.dtype)
print("Number of Dimensions:", salaries_array.ndim)
print("Shape:", salaries_array.shape)
print("Size:", salaries_array.size)

Ages Array:
[56 46 32 25 38 56 36 40 28 28]
Salaries Array:
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Ages Array Information:
Data Type: int64
Number of Dimensions: 1
Shape: (10,)
Size: 10
Salaries Array Information:
Data Type: int64
Number of Dimensions: 1
Shape: (10,)
Size: 10


## Answer To The Q2

In [4]:
ages_array = np.array(ages)
salaries_array = np.array(salaries)

highest_salary = np.max(salaries_array)
print("Highest Salary:", highest_salary)

lowest_salary = np.min(salaries_array)
print("Lowest Salary:", lowest_salary)

average_salary = np.mean(salaries_array)
print("Average Salary:", average_salary)

average_age = np.mean(ages_array)
print("Average Age:", average_age)

Highest Salary: 89735
Lowest Salary: 30769
Average Salary: 57446.9
Average Age: 38.5


## Answer To The Q3

In [5]:
ages_array = np.array(ages)
salaries_array = np.array(salaries)

condition = ages_array > 30
filtered_ages = ages_array[condition]

print("Ages greater than 30:")
print(filtered_ages)

count = np.sum(condition)
print("Number of employees older than 30:", count)

Ages greater than 30:
[56 46 32 38 56 36 40]
Number of employees older than 30: 7


## Answer To The Q4

In [15]:
ages_array = np.array(ages)
salaries_array = np.array(salaries)

updated_ages = ages_array + 5

print("Original Ages:")
print(ages_array)

print("Updated Ages (increased by 5 years):")
print(updated_ages)

Original Ages:
[56 46 32 25 38 56 36 40 28 28]
Updated Ages (increased by 5 years):
[61 51 37 30 43 61 41 45 33 33]


## Answer To The Q5

In [7]:
ages_array = np.array(ages)
salaries_array = np.array(salaries)

total_salary = np.sum(salaries_array)
print("Total Salary Expense:", total_salary)

max_salary = np.max(salaries_array)
min_salary = np.min(salaries_array)
salary_difference = max_salary - min_salary
print("Difference between Maximum and Minimum Salary:", salary_difference)

Total Salary Expense: 574469
Difference between Maximum and Minimum Salary: 58966


## Answer To The Q6

In [16]:
df = pd.read_csv("employees.csv")

print("First 5 rows:")
print(df.head())

print("Basic Information:")
print(df.info())

print("Summary Statistics:")
print(df.describe())

First 5 rows:
   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
Summary Statistics:
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


## Answer To The Q7

In [17]:
df = pd.read_csv("employees.csv")

selected_columns = df[["id", "age", "salary"]]
print("ID, Age, and Salary columns:")
print(selected_columns)

print("Last 3 rows:")
print(df.tail(3))

ID, Age, and Salary columns:
   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311
Last 3 rows:
   id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR


## Answer To The Q8

In [18]:
df = pd.read_csv("employees.csv")

it_employees = df[df["dept"] == "IT"]

print("IT Department Employees:")
print(it_employees)

total_it = len(it_employees)
print("Total number of IT employees:", total_it)

IT Department Employees:
   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
Total number of IT employees: 3


## Answer To The Q9

In [11]:
df = pd.read_csv("employees.csv")

sorted_df = df.sort_values(by="salary", ascending=False)

top_3_employees = sorted_df.head(3)

print("Top 3 Highest-Paid Employees:")
print(top_3_employees)

Top 3 Highest-Paid Employees:
   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR


## Answer To The Q10

In [19]:
df = pd.read_csv("employees.csv")

print("Original Salaries:")
print(df[["id", "salary"]])

df.loc[df["salary"] > 80000, "salary"] = 80000

print("Modified Salaries:")
print(df[["id", "salary"]])

new_average_salary = df["salary"].mean()
print("New Average Salary after replacement:", new_average_salary)

Original Salaries:
   id  salary
0   1   77191
1   2   74131
2   3   46023
3   4   71090
4   5   31685
5   6   30769
6   7   89735
7   8   86101
8   9   32433
9  10   35311
Modified Salaries:
   id  salary
0   1   77191
1   2   74131
2   3   46023
3   4   71090
4   5   31685
5   6   30769
6   7   80000
7   8   80000
8   9   32433
9  10   35311
New Average Salary after replacement: 55863.3
