<a href="https://colab.research.google.com/github/superraihan/Python/blob/main/Practice_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Multipal String

In [ ]:
massage ="""hey its me raihan nibir what's about you?
im a cse student """
print(massage)

hey its me raihan nibir what's about you?
im a cse student 


### ND Array Creation From Existing Data

In [ ]:
import numpy as np

matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [ ]:
import numpy as np
lst = [ 10,20,30,40,40.5]
arr =np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32


### Creating NDarray From Scratch

In [ ]:
#For zeros
import numpy as np
arr = np.zeros((2,3),dtype=np.int8)

print(arr)
print(arr.shape)

# For One

arr = np.ones_like((2,3),dtype=np.int8)

print(arr)
print(arr.shape)

# Empty

arr = np.empty((4,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)


[[0 0 0]
 [0 0 0]]
(2, 3)
[1 1]
(2,)
[[-13 -83 -66]
 [ 10   0   0]
 [  0   0   0]
 [  0   0   0]]
<class 'numpy.ndarray'>
(4, 3)
int8
2
12


### Array Creation With Random Values

In [ ]:
arr = np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[[0.46395284 0.23488275 0.82016506]
 [0.12989445 0.04405565 0.84809692]]
<class 'numpy.ndarray'>
(2, 3)
float64
2
6


## Array Creation With Range Functions





In [ ]:
# Scrial Number
arr = np.arange(1 , 10 , 1)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)
int64
1
9


In [ ]:
# For Matrix
arr = np.arange(1 , 10 , 1)
mat = arr.reshape(3,3)
print(arr)
print(mat)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(9,)
int64
1
9


In [ ]:
# Lin Space
arr = np.linspace(0 , 10 , 5)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[ 0.   2.5  5.   7.5 10. ]
<class 'numpy.ndarray'>
(5,)
float64
1
5


In [ ]:
# Log Space
arr = np.logspace(0, 4 , 6)
print(arr)


[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]


## Matrix For Linear Algebra

In [ ]:
import numpy as np
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [ ]:
# identy matrix
import numpy as np
identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [ ]:
arr = np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)


[1 0 0 0 5]


## Problem Solving

1. You have a list of temperatures recorded in Celsius. Your task is to:
Create a NumPy array from the given list.
Convert all temperatures from Celsius to Fahrenheit.The formula is F = C* 1.8 + 32.
Print the new Fahrenheit array.


In [ ]:
import numpy as np

celsius_list = [0, 10, 20, 30, 35.5, 100]

celsius_array = np.array(celsius_list)
print(f"Celsius Array: {celsius_array}")

fahrenheit_array = (celsius_array * 1.8) + 32

print(f"Fahrenheit Array: {fahrenheit_array}")

Celsius Array: [  0.   10.   20.   30.   35.5 100. ]
Fahrenheit Array: [ 32.   50.   68.   86.   95.9 212. ]


  You have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.
Print the array's shape, size, and data type.
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
Print the new array of lap times in minutes.


In [ ]:
import numpy as np

lap_times_seconds_list = [120, 115.5, 118, 121.2, 114]

lap_times_sec_arr = np.array(lap_times_seconds_list)

print(f"Original array: {lap_times_sec_arr}")
print(f"Shape: {lap_times_sec_arr.shape}")
print(f"Size: {lap_times_sec_arr.size}")
print(f"Data Type: {lap_times_sec_arr.dtype}")

print("-" * 30)

lap_times_min_arr = lap_times_sec_arr / 60

print(f"Lap times in minutes: {lap_times_min_arr}")

Original array: [120.  115.5 118.  121.2 114. ]
Shape: (5,)
Size: 5
Data Type: float64
------------------------------
Lap times in minutes: [2.         1.925      1.96666667 2.02       1.9       ]


## Numpy Array

In [3]:
import numpy as np
x =np.random.randint(1,10,size=(2,3))
y =np.random.randint(1,10,size=(1,3))
r = np.concatenate((x,y),axis=0)
print(r)


[[7 8 2]
 [3 7 7]
 [7 9 1]]


## Array Splitted

In [4]:
a = np.random.randint(1,10,size=(10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)

[9 7 5 5 1 9 1 8 2 2]
[array([9, 7, 5, 5]), array([1, 9, 1]), array([8, 2, 2])]


## Mathmatical Function

In [13]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([1, 2, 3, 4, 5])

sin_val = np.sin(x)
print("Value Of Sin:", sin_val)

# radian to degree conversion
deg_con =np.rad2deg(x)
print("Radian To Degree Conversion:", deg_con)

#Log
base_10_log_val=np.log10(x)
print("Log Value:", base_10_log_val)

Value Of Sin: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Radian To Degree Conversion: [ 572.95779513 1145.91559026 1718.87338539 2291.83118052 2864.78897565]
Log Value: [1.         1.30103    1.47712125 1.60205999 1.69897   ]


## Broadcasting

In [15]:
x = np.array([10, 20, 30, 40, 50])
result= x**2
print(result)


[ 100  400  900 1600 2500]
